id: A59245659
title: 'Beautiful Garland of Flowers: A Brief Prayer to the Successive Incarnations
  of Dzogchenpa Changchub Dorje'
type: translation
pechas:
- I50F0A2F1
- IBBAF9EB8
- I9699E492
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:44:22.835103
  last_modified_at: 2023-01-04 11:44:22.835113
  collections:
  - Dodrupchen Jigme Trinle Özer Series
  - Works of Tibetan Masters
alignment_to_base:
  I50F0A2F1/1E4E: 26F0
  IBBAF9EB8/18E3: 26F0
  I9699E492/7C3C: 26F0
